# Generated by Django 5.2.3 on 2025-06-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lastTradePrice', models.FloatField()),
                ('openPrice', models.FloatField()),
            ],
        ),
    ]
