# Generated by Django 5.2.3 on 2025-06-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockNames',
        ),
    ]
