# Generated by Django 5.2.3 on 2025-07-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
