# Generated by Django 5.2.3 on 2025-07-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_order_options_transaction_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='var',
            field=models.FloatField(default=0),
        ),
    ]
