# Generated by Django 5.2.3 on 2025-07-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_stock_var'),
    ]

    operations = [
        migrations.AddField(
            model_name='historystock',
            name='var',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='livestock',
            name='var',
            field=models.FloatField(default=0.0),
        ),
    ]
