# Generated by Django 5.2.3 on 2025-07-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_historystock_var_livestock_var'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='var',
        ),
    ]
